# Site
title:   "zenwalker.me"
slogan:  "Python, PHP, JavaScript разработчик"
url:     "http://zenwalker.me"
locale:  "ru"
baseurl: ""

author:
  email:   "zenwalker2@gmail.com"
  twitter: "zenwalker2"
  github:  "zenwalker"

# Source
source:      ./src
destination: ./build
plugins:     ./src/_plugins
layouts:     ./src/_layouts
data_source: ./src/_data

# Build
permalink:   /:year/:month/:title.html
markdown:    redcarpet
highlighter: null

# Assets
assets:
  js_compressor:  uglifier
  css_compressor: sass
  cache:          false

# Markdown
redcarpet:
  extensions: ["no_intra_emphasis", "autolink", "strikethrough", "superscript", "tables", "highlight"]
